### ISSUE TITLE
Change the current branch from 13.0 to 14.0 or 16.0

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/fleet#150]
Currently, the main branch of the project is at version 13.0. I would like to propose an update to version 14.0 or 16.0.

cc @ivantodorovich @simahawk

**Comment by ivantodorovich** [comment]
Makes sense to me 👍🏻 

I believe the process is creating a PR here: https://github.com/OCA/repo-maintainer-conf/blob/7a762e7c4c7c4b0aefccdf34d79a915d866db7e9/conf/repo/fleet.yml#L10

**Comment by marcelsavegnago** [comment]
done https://github.com/OCA/repo-maintainer-conf/pull/35
