### ISSUE TITLE
Weblate translation

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/fleet#29]
Hi,

Can someone please enable weblate translations for the fleet repository?

**Comment by pedrobaeza** [comment]
Which branch?

**Comment by pedrocs-exo** [comment]
12.0

**Comment by pedrobaeza** [comment]
I see that is enabled:

https://github.com/OCA/fleet/blob/12.0/.travis.yml#L21

**Comment by pedrocs-exo** [comment]
Thank you Pedro

It's not showing up in the translation project list though

**Comment by pedrobaeza** [comment]
@sbidoul maybe you can shed some light on this.

**Comment by sbidoul** [comment]
There are not `i18n/*.pot` files in this repo. This is most probably because Travis is misconfigured for this project.

**Comment by pedrobaeza** [comment]
Thanks for checking, Stéphane. Travis seems correct:

https://github.com/OCA/fleet/blob/12.0/.travis.yml#L21

**Comment by sbidoul** [comment]
I meant the travis environment variables that allow travis to push .pot files to GitHub. People tend to skip that step when configuring new repos... I just did it and restarted the builds for 13.0 and 12.0. Ping me again if it does not work.

**Comment by pedrobaeza** [comment]
Ah, right, I always forget that this part is needed!

Thanks.

**Comment by pedrocs-exo** [comment]
Thank you both!

For 13.0 everything is fine but 12.0 it is still missing on weblate. Can you pls check?

**Comment by sbidoul** [comment]
The travis job errored. I restarted again. It should be ok now.
