### ISSUE TITLE
[RFC] Proposal for new modules

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/fleet#40]
Hello guys,

I am working on an Odoo project with the purpose of serving car rental companies in the B2B model.

I understand that the fleet module is designed for the management and use of vehicles by the company that uses Odoo itself, but I believe that it is possible to extend some features to be able to attend this project.

Initial Scope
- Integrate the fleet.vehicle model with the agreement model (which can be of general use, for example to create an agreement for the use of the vehicle by employees)
- Integration with the Maintenance module to allow the creation of maintenance plans for vehicles
- Add types of inspections in the fleet.vehicle.inspection model (normal inspection, demobilization inspection and so on)

Modules that I intend to implement and make available at OCA
- fleet_vehicle_agreement
- fleet_vehicle_maintenance
- fleet_vehicle_inspection_type

What do you think of the modules mentioned above?

And what do you think of the project in general? I'm still thinking about the rental revenue management, I know it has the sale_rental module but I haven't analyzed it yet.

cc @ivantodorovich @mamcode @sbidoul @mymage @brian10048

**Comment by mymage** [comment]
Hi Marcel,
premise that I don't know much of Odoo modules and so I don't know if there is already a module to extend to manage agreements, I think that your approach is right.
I have only a doubt on the fleet_vehicle_inspection_type module because I think that this can be an utilitity to use on other "object" that you can maintain (eg buildings): so I think that it will be better to do a module that extend maintenance with inspections management, that in fact is a part of preventive maintenance. I think that this activity can be generalized as a list of checks to do.
Let me know when you propose a PR so I will give you a feedback.

**Comment by mamcode** [comment]
Hello @marcelsavegnago This sounds great, any help you need count on me :+1:

**Comment by mamcode** [comment]
Hello @marcelsavegnago I do not know the module Agreement yet but I see that the functionality of generating vehicle contracts is in the Fleet module, you evaluated if the functionality of native contracts serves for your project ?
 
![screenshot-localhost_8069-2021 03 28-11_44_50](https://user-images.githubusercontent.com/334317/112758339-63cf3380-8fdd-11eb-8e9a-7a28fd7e9699.png)

**Comment by marcelsavegnago** [comment]
@mamcode I know the functionality and will be used to post recurring costs. However, for this project I need to create a vehicle rental agreement and be able to identify which vehicles are part of this contract. Therefore, the modules of the project agreements seem to me to be the most suitable.

**Comment by marcelsavegnago** [comment]
> Hi Marcel,
> premise that I don't know much of Odoo modules and so I don't know if there is already a module to extend to manage agreements, I think that your approach is right.
> I have only a doubt on the fleet_vehicle_inspection_type module because I think that this can be an utilitity to use on other "object" that you can maintain (eg buildings): so I think that it will be better to do a module that extend maintenance with inspections management, that in fact is a part of preventive maintenance. I think that this activity can be generalized as a list of checks to do.
> Let me know when you propose a PR so I will give you a feedback.

@mymage The idea of the inspection module is to check various items of the vehicle on checkin and checkout. In this case, the type of inspection would be useful to separate the normal inspections of entry and exit and the inspections of mobilization / demobilization of the vehicle.

Talking about the inspection checklist for other objects I would do an extension for the maintenance module .. I will probably need this too.

**Comment by mymage** [comment]
What about add a flag "for checkin/checkout" to the generic inspection, or bettere add, if not alredy present, a category or type to the inspections?

**Comment by marcelsavegnago** [comment]
> What about add a flag "for checkin/checkout" to the generic inspection, or bettere add, if not alredy present, a category or type to the inspections?

I think it's a good one. I will implement the types of inspection and improve the interface a little.

Note. In the inspection we already have a field that identifies whether the inspection is Entry or Exit.

Soon I want to relate one inspection to the other to allow comparing the outgoing inspection with the inbound inspection of the vehicle.

**Comment by mamcode** [comment]
> @mamcode I know the functionality and will be used to post recurring costs. However, for this project I need to create a vehicle rental agreement and be able to identify which vehicles are part of this contract. Therefore, the modules of the project agreements seem to me to be the most suitable.

Hello @marcelsavegnago thanks for the clarification :+1:

**Comment by marcelsavegnago** [comment]
Just to keep you informed, I will focus on version 12.0 because of the Brazilian localization, which for now is stable in version 12.0 and will be important for the project that is financing the development. However, with the most robust and best tested modules, I migrate to version 13.0 and 14.0.

**Comment by bosd** [comment]
Do you plan to read out the health status of the vehicle?
Something like this on a recent odoo version would be handy.
https://engrasimulhaq.files.wordpress.com/2016/01/obdii-android-and-openerp-based-vehicles-3m-system.pdf

For preventative maintenance, vehicle tracking.
As well as odometer readout and mileage  logging for for tax purposes.

**Comment by marcelsavegnago** [comment]
> Do you plan to read out the health status of the vehicle?
> Something like this on a recent odoo version would be handy.
> https://engrasimulhaq.files.wordpress.com/2016/01/obdii-android-and-openerp-based-vehicles-3m-system.pdf
> 
> For preventative maintenance, vehicle tracking.
> As well as odometer readout and mileage logging for for tax purposes.

Hi @bosd ,
I find the idea very interesting. For now we have no budget to work directly on this type of functionality but it is something that can happen in the future.
